[project]
name = "uv_workspace"
version = "0.1.0"
description = "sis international app workspace"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "project_class"
]

[tool.uv.sources]
project_class = { workspace = true }

[tool.uv.workspace]
members = ["modules/*"]

